import { z } from 'zod';

/**
 * Item Specifics Schema
 * Represents eBay item specifics (brand, model, size, color, etc.)
 */
export const ItemSpecificsSchema = z.object({
  brand: z.string().optional(),
  model: z.string().optional(),
  size: z.string().optional(),
  color: z.string().optional(),
  material: z.string().optional(),
  style: z.string().optional(),
  condition: z.string().optional(),
  // Allow additional dynamic fields
}).passthrough();

export type ItemSpecifics = z.infer<typeof ItemSpecificsSchema>;

/**
 * Pricing Suggestion Schema
 * Represents AI-suggested price range with confidence
 */
export const PricingSuggestionSchema = z.object({
  min: z.number().positive(),
  max: z.number().positive(),
  suggested: z.number().positive(),
  confidence: z.number().min(0).max(1), // 0-1 scale
  currency: z.string().default('USD'),
  reasoning: z.string().optional(),
});

export type PricingSuggestion = z.infer<typeof PricingSuggestionSchema>;

/**
 * Listing Draft Schema
 * Complete listing draft generated by AI or edited by user
 */
export const ListingDraftSchema = z.object({
  title: z.string().min(10).max(80), // eBay title limits
  description: z.string().min(50).max(5000), // eBay description limits
  condition: z.enum([
    'New',
    'New (other)',
    'New with tags',
    'New without tags',
    'Pre-owned',
    'Used',
    'For parts or not working',
    'Seller refurbished',
    'Manufacturer refurbished',
  ]),
  itemSpecifics: ItemSpecificsSchema,
  pricing: PricingSuggestionSchema,
  categoryId: z.string().optional(),
  keywords: z.array(z.string()).default([]),
  aiConfidence: z.number().min(0).max(1).optional(),
  visibleFlaws: z.array(z.string()).optional(),
  // Metadata
  createdAt: z.string().datetime().optional(),
  updatedAt: z.string().datetime().optional(),
});

export type ListingDraft = z.infer<typeof ListingDraftSchema>;

/**
 * Job Status Schema
 * Represents the status of background jobs
 */
export const JobStatusSchema = z.enum([
  'pending',
  'processing',
  'completed',
  'failed',
]);

export type JobStatus = z.infer<typeof JobStatusSchema>;

/**
 * Job Type Schema
 * Types of background jobs
 */
export const JobTypeSchema = z.enum([
  'image_upload',
  'ai_analysis',
  'ebay_draft',
  'pricing_lookup',
]);

export type JobType = z.infer<typeof JobTypeSchema>;

/**
 * Job Schema
 * Complete job information
 */
export const JobSchema = z.object({
  id: z.string().uuid(),
  itemId: z.string().uuid(),
  type: JobTypeSchema,
  status: JobStatusSchema,
  errorMessage: z.string().nullable().optional(),
  metadata: z.record(z.unknown()).optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable().optional(),
});

export type Job = z.infer<typeof JobSchema>;

/**
 * Item Status Schema
 * Status of an item in the listing process
 */
export const ItemStatusSchema = z.enum([
  'draft',
  'processing',
  'ready',
  'published',
]);

export type ItemStatus = z.infer<typeof ItemStatusSchema>;

/**
 * Image Upload Schema
 * Represents an uploaded image
 */
export const ImageSchema = z.object({
  id: z.string().uuid(),
  itemId: z.string().uuid(),
  storagePath: z.string(),
  orderIndex: z.number().int().min(0),
  createdAt: z.string().datetime(),
});

export type Image = z.infer<typeof ImageSchema>;

